### PR TITLE
Update metasploit.sh

### PR DESCRIPTION
**Pull request by krisdowis**
I added the msfupdate command so it will be easier to update

### CODE REVIEW

**Comment by gushmazuko** [comment]
Thank you, but I already [added](https://github.com/gushmazuko/metasploit_in_termux/commit/81ab90be391d893b3413eb6120229dce9def0a90) that after reading your [comment](https://github.com/gushmazuko/metasploit_in_termux/issues/158#issuecomment-1193668291)

**Comment by krisdowis** [comment]
You only added the msfrpcd command

**Comment by gushmazuko** [comment]
Thanks

**Comment by krisdowis** [comment]
You are welcome

**Comment by krisdowis** [comment]
You only added msfrpcdSent from my Galaxy
-------- Original message --------From: gushmazuko ***@***.***> Date: 28/07/2022  12:36 pm  (GMT+01:00) To: gushmazuko/metasploit_in_termux ***@***.***> Cc: Praise Christopher ***@***.***>, Author ***@***.***> Subject: Re: [gushmazuko/metasploit_in_termux] Update metasploit.sh (PR #161) 
Thank you, but I already added that after reading your comment

**Pull request merged**
