### PR TITLE
Fixed an issue regarding Nokogiri version

### PR DESCRIPTION
**Pull request by dedshit**

### CODE REVIEW

**Comment by dedshit** [comment]
Old version of nokogiri and mini_portile2 are obsolete thats causes major problems during installation process

**Comment by Rahulv95** [comment]
Screenshot_2022-09-23-21-09-08-586_com termux
Help

**Comment by dedshit** [comment]
> Screenshot_2022-09-23-21-09-08-586_com termux Help

did you check my pr before you encountered this error ?

**Comment by dedshit** [comment]
@Rahulv95

### as far is know  **spell check ** error is due to old version of bundler 
Screenshot_20220924-091158_Termux

**Comment by Rahulv95** [comment]
So how can i fix it

**Comment by dedshit** [comment]
> So how can i fix it

you should not open a issue in PR.

**Comment by dedshit** [comment]
> So how can i fix it

open new issue and wait for owner to approve this

**Review by krisdowis — APPROVED** [review]

**Pull request merged**
